{
 "title": "Galaxy Node Detail",
 "tags": [ "galaxy" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "guest" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Process States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "blocked" ], "type": "alias" }
      ],
      [
       { "params": [ "dead" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "dead" ], "type": "alias" }
      ],
      [
       { "params": [ "paging" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "paging" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sleeping" ], "type": "alias" }
      ],
      [
       { "params": [ "stopped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "stopped" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buffered" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cached" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "send" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_path]] ([[tag_fstype]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Disk Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "alias": "[[tag_fstype]] @ [[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Network Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "TCP Session States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "select": [
      [
       { "params": [ "tcp_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "established" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_close" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "close" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_closing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "closing" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_fin_wait1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "fin_wait1" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_fin_wait2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "fin_wait2" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_listen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "listen" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_none" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "none" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_syn_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "syn_recv" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_syn_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "syn_sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Net Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "drop_in" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "drop_out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "err_in" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "err_out" ], "type": "alias" }
      ],
      [
       { "params": [ "ip_fragfails" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ip_fragfails" ], "type": "alias" }
      ],
      [
       { "params": [ "ip_reasmfails" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ip_reasmfails" ], "type": "alias" }
      ],
      [
       { "params": [ "icmp_inerrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "icmp_inerror" ], "type": "alias" }
      ],
      [
       { "params": [ "icmp_outerrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "icmp_outerrors" ], "type": "alias" }
      ],
      [
       { "params": [ "icmp_incsumerrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "icmp_incsumerrors" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_incsumerrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_incsumerrors" ], "type": "alias" }
      ],
      [
       { "params": [ "udp_incsumerrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "udp_incsumerrors" ], "type": "alias" }
      ],
      [
       { "params": [ "udplite_incsumerrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "udplite_incsumerrors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Received/Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}